version: '3.8'

services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: certiprof_backend
    ports:
      - "5000:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Server=172.29.99.8;Database=CERTIFICACIONES_BD;User Id=fsalazarmo;Password=3i5q32sNpf8B;TrustServerCertificate=True;MultipleActiveResultSets=true;
      - ASPNETCORE_ENVIRONMENT=Development
      - JWT_SECRET_KEY=${JWT_SECRET_KEY:-ThisIsASecureFallbackKeyForDevelopmentOnly123456789!}
      
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: certiprof_frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
